### ISSUE TITLE
Avoid using dynamic imports

### ISSUE THREAD

**Issue by dnemoga** [Zilliqa/Zilliqa-JavaScript-Library#107]
**Describe the bug**
See https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/eed3fbc01ca7c0036845ed1c6c31cf9a925ce94f/packages/zilliqa-js-crypto/src/random.ts#L19-L21
You are using `require('crypto')` under condition which causes errors while building apps via Webpack or Angular build tools.

**To Reproduce**
1. Create Angular app from scratch (e. g. using `@angular/cli`)
2. Add `@zilliqa-js/crypto` as a dependency
3. Try to use crypto features somewhere in the code
4. Profit

**Comment by noelyoo** [comment]
Hi, @dnemoga I followed the steps you mentioned and I got some result to help you out.

## Your possible issue
It seems like you experienced this error:
```
Module not found: Error: Can't resolve 'crypto' in '/.../node_modules/@zilliqa-js/account/dist'
ERROR in ./node_modules/@zilliqa-js/crypto/dist/index.umd.js
```

I can figure out the problem more precisely if you can provide your environment info and error logs.

## Solution
Only If it's the case, you can reference this issue [thread](https://github.com/angular/angular-cli/issues/1548#issuecomment-386871992) which is related to angular-cli

Therefore, you can follow [this](https://github.com/angular/angular-cli/issues/1548#issuecomment-427653778) to solve the issue.

Also, previously @iantanwx have figured this issue and made a PR to [Zilliqa-Wallet](https://github.com/Zilliqa/Zilliqa-Wallet) which is built with angular. You may want to check this [ian's PR](https://github.com/Zilliqa/Zilliqa-Wallet/pull/48) out.

FYI, I just made a working [react example](https://github.com/noelyoo/react-zilliqajs-demo/commits/master) with CRA and TypeScript.

**Comment by iantanwx** [comment]
Thanks @noelyoo. Yes overriding the webpack config will work. Alternatively you may want to try emitting commonjs modules from typescript instead of esnext, although I have not tested this approach.

**Comment by noelyoo** [comment]
@iantanwx Sure, that approach will do.
