### ISSUE TITLE
Force signature String to be length=128

### ISSUE THREAD

**Issue by neeboo** [Zilliqa/Zilliqa-JavaScript-Library#112]
**Is your feature request related to a problem? Please describe.**
When signature is send to rpc, if the signature length is not 128, it will be rejected

**Describe the solution you'd like**
Force signature string length inside `schnorr.Sign` method 

**Describe alternatives you've considered**

// ....

export const sign = (
  msg: Buffer,
  privKey: Buffer,
  pubKey: Buffer,
): Signature => {
  const prv = new BN(privKey);
  const drbg = getDRBG(msg);
  const len = curve.n.byteLength();

  let sig;
  while (!sig) {
    const k = new BN(drbg.generate(len));
    const trySig = trySign(msg, k, prv, pubKey);
    sig =checkValidSignature(trySig) ? trySig : null;
  }

  return sig;
};

/**
 * verify if signature is length===128
 * @function checkValidSignature
 * @param  {Signature} sig Signature
 * @return {boolean}
 */
export const checkValidSignature = sig:Signature => {
  return sig.r.toString('hex').length + sig.s.toString('hex').length === 128
}

```
Edit: Something like that

**Comment by iantanwx** [comment]
Thanks @neeboo, I’ll fix this tomorrow.
