### ISSUE TITLE
Addition of presets for Mainnet and Testnet

### ISSUE THREAD

**Issue by evesnow91** [Zilliqa/Zilliqa-JavaScript-Library#134]
**Is your feature request related to a problem? Please describe.**
Currently, there are a few variables that changes along with the different networks being used. For example:
- `CHAIN_ID` (`1` for Mainnet, `333` for Testnet)
- `MSG_VERSION` (Currently `1` but might change in the future)
- `HRP` (`zil` for Mainnet, `tzil` for Testnet)
- URL Endpoint (`https://api.zilliqa.com` for Mainnet, `https://dev-api.zilliqa.com` for Testnet)

**Describe the solution you'd like**
Add some presets so that we can imply which is the active chain for the script we are writing.
Example:
```
chain.set_active_chain(chain.MainNet)
```
Extracted from [PyZil implementation](https://github.com/deepgully/pyzil#set-active-chain-mainnet-or-testnet).

It can be located in an `.env` file with details specified as above, so devs can add more presets for other networks if they wish to.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by neeboo** [comment]
https://github.com/neeboo/Zilliqa-JavaScript-Library/blob/enhance/neeboo/packages/zilliqa/src/index.ts

I edited the entry setting , see if it works.

however, not sure about where to put `HRP`.

If we only use `bech32` as display or validating on Address format, I simply add a `Bech32TestNet` format.

**Comment by renlulu** [comment]
As I talked with [@neeboo](https://github.com/neeboo) offline, It might be some problem if we use .env file to locate the pre define configurations under the browser environment. I am not sure about this.

**Comment by evesnow91** [comment]
@noelyoo how did you managed .env for nucleus-wallet?

@neeboo I think we can scrap `tzil` if it complicates things and just use `CHAIN_ID` instead. As for `MSG_VERSION`, this can only change with a Zilliqa Improvement Proposal in future. I think we can preset it?

**Comment by edisonljh** [comment]
Using `.env` to manage presets might cause production errors. 

I think the preset is better done with an enums that can be imported, ideally from `zilliqa-js/util`.

**Comment by noelyoo** [comment]
@evesnow91 Hi, `.env` configuration of Nucleus Wallet is irrelevant to this issue.

**Comment by iantanwx** [comment]
Just going to weigh in here. Since already use CHAIN_ID, I think this additional level of differentiation doesn't add much security wise. It's ultimately up to @renlulu and @evesnow91 to decide whether or not to deal with the complexity going forward. Keep in mind we have to cascade changes to other SDKs, used in very large scale production systems. My 2 cents as a contributor is therefore not to add the additional HRP unless there's a wider effort to do so at the protocol level.

**Comment by iantanwx** [comment]
Also, please don't rely on .env at the library level. A library should not generally rely on environmental variables for anything if possible.

**Comment by neeboo** [comment]
there is potential problem with enum when developer is not using Typescript and use es5 directly.

We'd better use `Object.freeze({...})` to it
