### ISSUE TITLE
Transaction.senderAddress getter return an invalid address

### ISSUE THREAD

**Issue by krisboit** [Zilliqa/Zilliqa-JavaScript-Library#139]
**Describe the bug**
Transaction.senderAddress returns an invalid address.

**To Reproduce**
1. Using zilliqajs lib:
```
const zilliqa = new Zilliqa('https://dev-api.zilliqa.com');
const txInfo = await zilliqa.blockchain.getTransaction("fc924aa57bd5dc924629fff1553a10bc99e1edf1f1db717f2b7e2da7f7c6e616");
console.log(txInfo.senderAddress); // 0x878a9eC7A7791a5DB57746b1a8ba2C46410bc4f4
```
2. Opening https://viewblock.io/zilliqa/tx/0xfc924aa57bd5dc924629fff1553a10bc99e1edf1f1db717f2b7e2da7f7c6e616?network=testnet
sender is: zil1kjkadrcz80rsqeq5rdvv4crqesth7l2q8fnl48 -> **0xb4Add68f023Bc70064141B58cAE060Cc177f7d40**

**Expected behavior**
txInfo.senderAddress to be 0xb4Add68f023Bc70064141B58cAE060Cc177f7d40

**Additional context**
From my investigation it seems that in `Transaction.senderAddress` when calling `getAddressFromPublicKey()` `0x` should be removed from the public key.

**Comment by neeboo** [comment]
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/2592722a8bcf9a57aabff896ddfed3563a5e200c/packages/zilliqa-js-blockchain/src/util.ts#L40

should fix here

```javascript
return {
   ...
    pubKey: senderPubKey.replace('0x', ''),
    ...
  };
```
