### ISSUE TITLE
Smart contract address is not correctly filled on contract deploy

### ISSUE THREAD

**Issue by krisboit** [Zilliqa/Zilliqa-JavaScript-Library#143]
**Describe the bug**
When deploying a smart contract the address that is set on the contract instance is not correct. The issue is because of using a provider and some parameters used by `Contracts.getAddressForContract()` are not set.

**To Reproduce**
I will give an example. Lets say we have a dApp that has this code:
```
new Zilliqa('', moonlet.providers.zilliqa);
const code = `...contract code...`;
const init = `...init params...`

// Instance of class Contract
const contract = this.state.zilliqa.contracts.new(code, init);

// Deploy the contract
const [deployTx, hello] = await contract.deploy({
    gasPrice: units.toQa('1000', units.Units.Li),
    gasLimit: Long.fromNumber(10000)
});
```
`hello.address` is an incorrect address because the deployment transaction doesn't have the `pubKey` and `nonce` fields set, these are filled automatically by moonlet.

**Expected behavior**
`hello.address` should be correctly resolved, one possible solution is to get the contract address from the response of the deployment request.

**Comment by neeboo** [comment]
Then we should first import 

```javascript
import { toChecksumAddress } from '@zilliqa-js/crypto';
```

https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/6ad8b82603854bec290ad41997ca0130ecd43a71/packages/zilliqa-js-contract/src/contract.ts#L109

```javascript
 @sign
  async prepareTx(
    tx: Transaction,
    attempts: number = GET_TX_ATTEMPTS,
    interval: number = 1000,
  ): Promise<Transaction> {
    const response = await this.provider.send<DeploySuccess, DeployError>(
      RPCMethod.CreateTransaction,
      { ...tx.txParams, priority: tx.toDS },
    );

    if (response.error) {
      this.address = undefined;
      return tx.setStatus(TxStatus.Rejected);
    }
    this.address = toChecksumAddress(response.result.ContractAddress);
    return tx.confirm(response.result.TranID, attempts, interval);
  }
```

and here
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/6ad8b82603854bec290ad41997ca0130ecd43a71/packages/zilliqa-js-contract/src/contract.ts#L167

```javascript
this.address =
        this.address && isValidChecksumAddress(this.address)
          ? this.address
          : Contracts.getAddressForContract(tx);

```
