### ISSUE TITLE
Zilliqa address standard, for testnet

### ISSUE THREAD

**Issue by krisboit** [Zilliqa/Zilliqa-JavaScript-Library#145]
**Describe the bug**
Bech32 util functions `fromBech32Address`, `toBech32Address`, `isBech32` are not following 100% the address standards from here: https://github.com/Zilliqa/Zilliqa/wiki/Address-Standard

The problem is that it doesn't handle testnet addresses.

**Expected behavior**
To be possible to transform and validate testnet addresses.

**Additional context**
A possible fix would be to change the interface of the functions:
```
export const isBech32 = (raw: string, testnet:boolean = false) => { ... }
export const toBech32Address = (address: string, testnet:boolean = false): string => { ... }
export const fromBech32Address = (address: string, testnet:boolean = false): string => { ... }
```
this way it's backward compatible with current implementations

**Comment by evesnow91** [comment]
We will be scrapping `tzil` requirement for testnet, it will use the same `zil` prefix as mainnet. Reason is because `CHAIN_ID` already serves as a safeguard against wrong network broadcast.
