### ISSUE TITLE
Support ES Module (ESM) standard 

### ISSUE THREAD

**Issue by Meai1** [Zilliqa/Zilliqa-JavaScript-Library#147]
Please make compatible with ES Module (ESM) standard as required by: 
https://github.com/pikapkg/web

Regular webpack output is 2MB. Very bad if this has to be downloaded everytime I make a new modification to my own user code bundle and it gets bundled together.

**Comment by iantanwx** [comment]
@Meai1 you can import the sub packages independently in that case...
