### ISSUE TITLE
Unable to deploy contract in sample testBlockchain() code

### ISSUE THREAD

**Issue by cloudwheels** [Zilliqa/Zilliqa-JavaScript-Library#164]
**Describe the bug**
I have created a testnet (Nucleus) wallet and funded it from the faucet.
Using the sample testBlockchain() code provided (on Readme.md) I can access the account and make the first transaction, but receive (unhelpful) error codes in the transaction receipt when attempting to deploy the HelloWorld contract, i.e. deployment fails
The output is shown below.
I have made various attempts to chenge the gas price and/or limit or replace the contract code which have not helped. 

On some occasions the transaction times out without confirmation after 33 attempts. I also had some problems initially running on node 12.0 but I don't think this is relevant to this issue.

```
My account address is: 0x4d2593679d0367C07F5a9Cb906357FC2B23be25e
My account bech32 address is: zil1f5jexeuaqdnuql66njusvdtlc2erhcj72qpdv8
Your account balance is:
{ balance: '182149000000000', nonce: 7 }
Current Minimum Gas Price: 1000000000
My Gas Price 1000000000
Is the gas price sufficient? true
The transaction status is:
{ cumulative_gas: 1, epoch_num: '785548', success: true }
Deployment Transaction ID: e84ce76cc8d88d6c15cfccc22eb5b575a986604c36d10b078e62837a54c8033d
Deployment Transaction Receipt:
{ cumulative_gas: 1214,
  epoch_num: '785551',
  errors: { '0': [ 9, 1 ] },
  success: false }
The contract address is:
undefined
Contract has not been deployed!
```

**Comment by cloudwheels** [comment]
I will open a PR with this fix but for now, at line 111:
```
value: `0x${address}`
```
REMOVING THE LEADING ` 0x` (as the `address` is already returned with this) will enable successful deployment of the contract. ie, change this line to:
```
value: `${address}`
```

There are however other errors arising after this (contract not initialised) so keeping this issue open.

**Comment by cloudwheels** [comment]
I have created a repo at https://github.com/cloudwheels/Zilliqa-Node-Starter-Basic which contains (temporary) fixes for the issues I have experienced with the example quickstart code.

**Comment by renlulu** [comment]
Thanks for your help, as we discussed on discord, let's close this issue then move to #165, also I will take a good care of your quickstart, thanks for your effort!
