### ISSUE TITLE
Contract.call() does not persist Contract.address?

### ISSUE THREAD

**Issue by cloudwheels** [Zilliqa/Zilliqa-JavaScript-Library#165]
**Describe the bug**
I have been working through the example code on README.md
I experienced an issue #164 deploying the contract which appears to be due to a bug in the example code.
After resolving the above, the sample HelloWorld contract deploys successfully, and the `Contract.call()` method is successfully executed to invoke the setMessage transition.
However, the subsequent call to `getState()` fails with `Error: Cannot get state of uninitialised contract `

**To Reproduce**
Run sample code in README.md (having fixed problem described in #164 ) 

**Expected behavior**
State of newly deployed HelloWorld contract should be returned.

**Additional context**
It appears the Contract object loses its `address` property after execution of the` call()` method.

The error is being thrown in `getState()` at the lines below, but the actual problem would appear to be in `call()`, which does not appear to perist the `address` property on the Contract object returned. (?)
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/48a2d4887f61452ebf6cd266411380ffe24e7b0f/packages/zilliqa-js-contract/src/contract.ts#L237-L239

**Comment by cloudwheels** [comment]
My quick and dirty hack  to get the sample code running is to assign the hello Contract to a new Contract object before executing `call()`.
Then execute `getState()` against this new contract object, e.g.:
```js
//deploy contract 
// ...
//assign 'hello' contract to new object
const deployedContract = zilliqa.contracts.at(hello.address);
//execute hello.call() to invoke setHello transition
// ...
//execute getStatus against the duplicated deployedContract
const state = await deployedContract.getState();
// ...
```
 
I will fork the project and investigate/fix the possible bug in `Contract.call()`.

**Comment by cloudwheels** [comment]
@renlulu - have opened this issue to track what I think is a bug, as discussed on discord. Have forked to take a better look - bear with me or jump in yourself!

**Comment by renlulu** [comment]
In general, it's more make sense to separate contract deployment with contract invocation, because it is more often to deal with an exist smart contract. But we still need to figure out why the address got missed while deploying procedure. As we discussed before, we can update here later.

**Comment by renlulu** [comment]
By the way, I have took a look at your quick start, it works, very nice!

**Comment by renlulu** [comment]
Hi @cloudwheels I debug this for a while, the conclude is `@zilliqa-js/zilliqa": "0.6.3` is totally okay, but it indeed some issue with the version `@zilliqa-js/zilliqa": "^0.8.0-alpha.0` mostly inner `prepareTx` function

**Comment by renlulu** [comment]
So you can use the stable version first. I will take a look on the branch of the `"^0.8.0-alpha.0`.
