### ISSUE TITLE
Known bug with Node 12^ due to scrypt

### ISSUE THREAD

**Issue by edisonljh** [Zilliqa/Zilliqa-JavaScript-Library#176]
**Describe the bug**

Zilliqa JS does not work on node 12.x onwards. Temporarily fix https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/172 only resolved some issues for some users.

More permanent fix must be found. 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.11.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command \"/usr/local/Cellar/node/12.11.1/bin/node\" \"/usr/local/Cellar/node/12.11.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/edison/code/scratch/zil-test/node_modules/scrypt
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
```

This issue is likely to be related to https://github.com/ethereum/web3.js/issues/2913#issuecomment-510643036

`web3.js` solves this problem in this PR, and it is likely that we will need a similar approach to handle the two different environment (node 12^ vs node 12 and below)

https://github.com/ethereum/web3.js/pull/2938/files

**Comment by bb111189** [comment]
long overdue but current `dev` branch now have support up to node 14 LTS

#276
