### ISSUE TITLE
Version 0.11.0 has breaking changes

### ISSUE THREAD

**Issue by bogdan** [Zilliqa/Zilliqa-JavaScript-Library#232]
**Describe the bug**

Version 0.11.0 changes the behavior of `zilliqa.contracts.at(address)` and `zilliqa.transactions.new({toAddr})` which happens without any backward compatibility, warning or changelog  in a minor version release.  

**To Reproduce**

Call the following code on 0.8.x and 0.11.0:

```
zilliqa.contracts.at("0xd90f2e538ce0df89c8273cad3b63ec44a3c4ed82")
```
 
**Expected behavior**

Both versions work ok

**Comment by bb111189** [comment]
PR #241

**Comment by bb111189** [comment]
Fixes released in https://github.com/Zilliqa/Zilliqa-JavaScript-Library/releases/tag/v0.11.1
