### ISSUE TITLE
cannot deploy a contract

### ISSUE THREAD

**Issue by eujinong123** [Zilliqa/Zilliqa-JavaScript-Library#257]
I wanted to deploy a contract on Zilliqa chain (testnet) with my wallet but couldn't do it by using `Contract.prototype.deploy` of `@zilliqa-js/contract`.

I was able to get the contract address by using `Contract.prototype.deployWithoutConfirmation`, and with this address, confirmed its deployment status (`isDeployed` returned `true`, `isRejected` returned `false` and the contract's `ContractStatus` was `0`.)
However, inspite of all these, I couldn't find the corresponding transaction history on [Block exploerer for testnet](https://viewblock.io/zilliqa) and couldn't import the deployed contract on [IDE](https://ide.zilliqa.com/), either.

Node.js app always tells the contract has been deployed but nothing could be from the truth.

**Comment by eujinong123** [comment]
I confirmed this repo's [example code](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/examples/deployContract.js) works correctly but when I substituted the private key with mine, a contract wasn't deployed even after 33 attempts.
My current balance is 278.864 ZIL so it was sufficient to do the transaction.

Could you help me understand this circumstance?

**Comment by renlulu** [comment]
Hey, can you provide your contract code (and init.json)? Would like to see the detail of your deploying script.

**Comment by eujinong123** [comment]
https://github.com/arnavvohra/document-store/blob/master/DocumentStore.scilla
`[
					{
						type: 'ByStr20',
						value: `${publicKey}`,
						vname: 'contract_owner'
					},
					{
						type: 'String',
						value: 'NextCertStore',
						vname: 'name'
					},
					{
						type: 'String',
						value: '1.0',
						vname: 'version'
					},
					{
						vname: '_scilla_version',
						type: 'Uint32',
						value: '0',
					}
				]`

https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/examples/deployContract.js
`[
      // this parameter is mandatory for all init arrays
      {
        vname: '_scilla_version',
        type: 'Uint32',
        value: '0',
      },
      {
        vname: 'owner',
        type: 'ByStr20',
        value: `${address}`,
      },
    ]`

The obvious thing is that when I tested your [example code](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/examples/deployContract.js), I just changed only the private key value with mine. After that, it stopped working. Really weird to me.
Thanks for your response.

**Comment by eujinong123** [comment]
Simple change of an account (private and public key change) resolved my issue.
How can I get a stable wallet account?

**Comment by renlulu** [comment]
`{ type: 'ByStr20', value: ${publicKey}, vname: 'contract_owner' }` should be `${address}` not public. To get a test account, you can try `https://dev-wallet.zilliqa.com`, try to generate one and get some test zils.

**Comment by renlulu** [comment]
You can also join our discord, `https://discord.gg/aRyReY`

**Comment by eujinong123** [comment]
Okay, thanks.
