### ISSUE TITLE
Incorrect GetPendingTxn 'info' message when TX is not confirmed

### ISSUE THREAD

**Issue by rockacola** [Zilliqa/Zilliqa-JavaScript-Library#261]
**Describe the bug**

`GetPendingTxn` returns `Txn already processed and confirmed` despite it's not yet confirmed.

**To Reproduce**

1. Make a transaction on testnet using [Nucleus Wallet](https://dev-wallet.zilliqa.com/send)
2. Obtain the transaction ID upon success
3. Perform `GetPendingTxn` with the transaction ID before it's been confirmed
4. Notice the response, where the "info" states the transaction is confirmed despite `confirmed: false`

```js
{
  code: 0,
  confirmed: false,
  pending: false,
  info: 'Txn was already processed and confirmed'
}
```

**Expected behavior**

Modified "info" message that better describe status of `code: 0`.

**Comment by rockacola** [comment]
It seems `GetPendingTxn` JSON-RPC API method will response with `code: 0` whether it's confirmed, or pending or not. 

My suggestions:

* To either change the ["info" message for `code: 0`](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/e4386e5c8b3e0d7b8177ff0c40ba0016af4b3425/packages/zilliqa-js-blockchain/src/chain.ts#L48) into a broader, more accurate description; or 
* To modify [`pendingErrorMap` method](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/e4386e5c8b3e0d7b8177ff0c40ba0016af4b3425/packages/zilliqa-js-blockchain/src/chain.ts#L47-L70) to accept `confirmed` and `pending` values.

**Comment by bb111189** [comment]
The new api to track txn status will be at https://dev.zilliqa.com/docs/apis/api-transaction-get-transaction-status
