### ISSUE TITLE
View transactions from address function

### ISSUE THREAD

**Issue by ArthurHoeke** [Zilliqa/Zilliqa-JavaScript-Library#263]
**Is your feature request related to a problem? Please describe.**
Currently the account package misses a function to fetch all in/out transactions per address. A function like this is handy for products like wallets, and currently has to be fetched via a web API

**Describe the solution you'd like**
A new function in the account package to fetch transactions per address.

**Additional context**
I'm developing an Ionic app which currently has to fetch the transaction history per account via a web API on viewblock.io

**Comment by bb111189** [comment]
This is unfortunately not possible as the blockchain API does not provide it and it will be too disk-consuming for nodes to store it separately for such API. 

The current way is to traverse through the chain to get the complete history per address. We have a separate off-chain solution for this at https://github.com/Zilliqa/Devex-apollo
