### ISSUE TITLE
Sometimes transactions fail to confirm without clear reason

### ISSUE THREAD

**Issue by ArthurHoeke** [Zilliqa/Zilliqa-JavaScript-Library#266]
**Describe the bug**
When creating a transaction sometimes it seems to fail without clear reason. There's no out of gas error, simply 'not confirmed after 33 blocks'.
![image](https://user-images.githubusercontent.com/34348870/99302425-aa529b80-284f-11eb-8340-ee80aa67fcc2.png)

**To Reproduce**
I'm using the following code:
```const tx = zilliqa.blockchain.createTransaction(
            zilliqa.transactions.new(
              {
                version: VERSION,
                toAddr: user.address,
                amount: new BN(units.toQa(withdraw, units.Units.Zil)),
                gasPrice: units.toQa('20000', units.Units.Li),
                gasLimit: Long.fromNumber(2),
              },
              false,
            ),
        );```

**Comment by lokoArt** [comment]
Same thing. Any update on it? How to mitigate these issues?

**Comment by lokoArt** [comment]
Starting from Dec 25, almost all transactions fail by this reason. Hope someone will give a suggestion on how to solve it...

**Comment by ArthurHoeke** [comment]
> Starting from Dec 25, almost all transactions fail by this reason. Hope someone will give a suggestion on how to solve it...

I've recently discovered the problem, it's caused by if two transactions are sent at the same time whilst the first transaction of the two hasn't confirmed yet. The library doesn't keep track of the nonce from the unconfirmed transaction, causing the second transaction to use the last confirmed transaction's nonce. In other words, two transactions are sent with the same nonce causing one to fail.

You'll have to create a variable which increments for every transaction and add that variable to the nonce property of the zilliqa.transactions.new
