### ISSUE TITLE
Consider the case of offline signing

### ISSUE THREAD

**Issue by renlulu** [Zilliqa/Zilliqa-JavaScript-Library#275]
**Is your feature request related to a problem? Please describe.**
Inside wallet methods, there is a pre-checking on balance before signing it. But in the case of offline signing, there is no such Internet connection which means the code cannot be executed successfully. 

**Describe the solution you'd like**
Put a flag (maybe named checkBalance) whose default value is yes, which would not break current user code. Those who want to bypass the checking can pass `false` explicitly.

**Comment by daynight97** [comment]
Hi @renlulu @teye  Any progress on this?

**Comment by bb111189** [comment]
Implemented and will be release in upcoming release
