### ISSUE TITLE
Engine "node" incompactible with version 15.10.0

### ISSUE THREAD

**Issue by RubenK77** [Zilliqa/Zilliqa-JavaScript-Library#287]
Hi i ran the command
` yarn add @zilliqa-js/zilliqa `
got the error:
`@zilliqa-js/blockchain@2.2.1: The engine "node" is incompatible with this module. Expected version ">=10.0.0 <15". Got "15.10.0"`

- OS: Manjaro

Can I run `yarn add @zilliqa-js/zilliqa` with the `--ignore-engines` flag?

**Comment by RubenK77** [comment]
This might be a problem with node I had the same error with tslib

**Comment by teye** [comment]
Hi, the sdk supports up to the latest LTS version. Currently, it is NodeJS 14.

The sdk may still be installed with `--ignore-engines` flag, however, there is no guarantee that it is compatible with NodeJS 15.

**Comment by fabianriewe** [comment]
Are there any known bugs for node version 15?

**Comment by teye** [comment]
@fabianriewe 
We haven't tested Node 15 and have no plans to update the library to support 15 currently.  A difference in the major version may sometimes require new versions of typescript or other libraries. Hence, use it at your own discretion.
