### ISSUE TITLE
Nuxtjs and (2.3.0-alpha.0) version won't build ? using 0.11.1 works fine

### ISSUE THREAD

**Issue by re2005** [Zilliqa/Zilliqa-JavaScript-Library#303]
**Describe the bug**

```
* fs in ./node_modules/node-gyp-build/index.js
```

**To Reproduce**
Generate a project using nuxt, install and import the latest version of this SDK.

`npm run dev`

**Expected behavior**
To not give an error on build

**Desktop (please complete the following information):**
 - OS: Mac
 - Node: 14.5

**Comment by teye** [comment]
Hi, I believe there is an output from the console to install `fs` like this:
![nuxt_zilliqajs](https://user-images.githubusercontent.com/6906654/120148969-9b479f80-c21b-11eb-94e8-ab299be29b45.png)

Could you try and let us know again?

**Comment by re2005** [comment]
Hi @teye I've tried again, all from scratch and doesn't seems to work for me.

Could you please indicate what node/npm version are you using? Or if you have a Docker image or repo where I can run the same configuration?

Thanks!

**Comment by re2005** [comment]
It turns that by adding the following code to the `nuxt.config.js` it will work just fine.


```
// Build Configuration: https://go.nuxtjs.dev/config-build
build: {
    extend (config) {
      config.node = {
        fs: 'empty'
      }
    }
}
```
