### ISSUE TITLE
Crypto module Hdkey

### ISSUE THREAD

**Issue by realsteel85** [Zilliqa/Zilliqa-JavaScript-Library#312]
**Describe the bug**
@Zilliqa/account uses HDkey. Hdkey uses Crypto. Unfortunately this one is deprecated. This prevents us from building our react-native app.

**To Reproduce**
Package.json
"@zilliqa-js/account": "^3.0.0",
    "@zilliqa-js/core": "^3.0.0",
    "@zilliqa-js/crypto": "^3.0.0",
    "@zilliqa-js/proto": "^3.0.0",
    "@zilliqa-js/util": "^3.0.0",
    "@zilliqa-js/zilliqa": "^3.0.0",

run a react native app in expo environment    
![Untitled-1](https://user-images.githubusercontent.com/68297405/125669419-5c7af7ca-ea60-455f-926e-c21a7866843e.png)

possible solution:
"hdkey": "https://github.com/cryptocoinjs/hdkey#browserFriendly"

**Comment by AmritKumar** [comment]
@renlulu Can we take a look at it?

**Comment by realsteel85** [comment]
@renlulu i can share a git With the code of the project if you want.

**Comment by teye** [comment]
@realsteel85 can you share with us a sample code to reproduce the error?

**Comment by realsteel85** [comment]
I have made a simpel project for reproduce the error. 
https://github.com/realsteel85/cryptoError

**Comment by teye** [comment]
> I have made a simpel project for reproduce the error.
> https://github.com/realsteel85/cryptoError

Thanks looking into it.

**Comment by teye** [comment]
@realsteel85 I have managed to resolve the issue.
![image](https://user-images.githubusercontent.com/6906654/127142156-82f7b5c9-5856-4e34-bf7d-6aead87fa397.png)

The above project reads the address and invokes a `GetBalance` API to retrieve the user balance. The user balance is saved in a `React.State` and displayed on screen.

Please check out the updated project at: https://github.com/teye/react-native-zilliqa-js.

The issue isn't with a deprecated package but rather `react-native` itself isn't able to read `NodeJS` native modules such as `crypto`, `fs` and others. See https://gist.github.com/parshap/e3063d9bf6058041b34b26b7166fd6bd.

Hence to resolve it, we need to first install "react-native" replacements:
```
yarn add node-libs-react-native
yarn add react-native-fs
```

Next, configure `metro.config.js` to replace the native node modules with the newly downloaded ones:
```
// others ...
module.exports = {
  resolver: {
    extraNodeModules: {
      ...require('node-libs-react-native'),
      fs: require.resolve('react-native-fs')
    }
  },
};
```

Finally, import it before the app is initialized, e.g. in `index.js`:
```
import 'node-libs-react-native/globals';    <-- add this
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

**Comment by realsteel85** [comment]
thnxs a lot !!!
