### ISSUE TITLE
Unsuccessful contract call will reset addresses

### ISSUE THREAD

**Issue by bb111189** [Zilliqa/Zilliqa-JavaScript-Library#317]
**Describe the bug**
Unsuccessful calls to contracts in ZilliqaJS reset their addresses to undefined, effectively making them unavailable for further transactions.

Note: Feedback from the Chainsecurity team

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noel-yoo** [comment]
It's lacking the details to reproduce issue.
Let's reopen this when we have enough info.
