### ISSUE TITLE
unused dependency request.js in /lib/node.js

### ISSUE THREAD

**Issue by neeboo** [Zilliqa/Zilliqa-JavaScript-Library#33]
path: Zilliqa-JavaScript-Library/lib/node.js

**Comment by noelyoo** [comment]
I created a PR for this issue:
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/34
@neeboo

**Comment by noelyoo** [comment]
@neeboo 
This issue has been resolved. https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/34

**Comment by neeboo** [comment]
@noelyoo

thanks

**Comment by noelyoo** [comment]
Would you close this issue?
