### ISSUE TITLE
getTransaction API to return transaction fee

### ISSUE THREAD

**Issue by scovic** [Zilliqa/Zilliqa-JavaScript-Library#378]
As title says, getTransaction API method doesn't return fee of the transaction. 
Only other way to get fee is to use viewblock api,  i t would be good to get around that.

**Comment by noel-yoo** [comment]
Hi @scovic, you can calculate as the following:
`transaction fee = cumulative gas * gas price`

No need to be included in `getTransaction` since it's easy to calculate.

Thanks
