### ISSUE TITLE
RUST SDK support for Zilliqa

### ISSUE THREAD

**Issue by amitcz** [Zilliqa/Zilliqa-JavaScript-Library#387]
Schnorr implementation has been implemented differently in Javascript, Golang and Python.
I tried to implement the same in RUST for creating signature component but got lost somewhere.

Looking forward from the development team to provide Rust SDK.
As rust is fast and major projects are moving towards RUST.

Any timeline for this would be highly appreciated...

**Comment by bb111189** [comment]
We currently have no plan to create a RUST SDK. However, feel free to ask us any questions if you are lost. 
We will also welcome community members to build and maintain a community rust SDK.
