### ISSUE TITLE
Minimizing build size

### ISSUE THREAD

**Issue by edisonljh** [Zilliqa/Zilliqa-JavaScript-Library#48]
Library size is huge! We should mindful about the packages we are importing. Also, we need to perform code review and perform some refactoring to minimise build. For one, we have unused dependencies and various of crypto libs that we do not use.

Ideas or PRs for minimising library size are absolutely welcome. :)

**Comment by iantanwx** [comment]
Closing as bundle size has come down to 18x kb in #54.
