### ISSUE TITLE
Automated Testing for the APIs

### ISSUE THREAD

**Issue by edisonljh** [Zilliqa/Zilliqa-JavaScript-Library#53]
**Is your feature request related to a problem? Please describe.**
The API is tested manually, typically through a script which i've uploaded to `test/script/script.js`. No engineers like to develop test cases, but someone has to do it! Even the script does not test every function that this API lib has. 

**Describe the solution you'd like**
Chai

**Describe alternatives you've considered**
Testing is done manually through Postman or the test script `test/script/script.js`.

**Comment by iantanwx** [comment]
Ported to Jest, added CI in #54. Closing.
