### ISSUE TITLE
Missing bound checks on Schnorr signature components. 

### ISSUE THREAD

**Issue by AmritKumar** [Zilliqa/Zilliqa-JavaScript-Library#93]
**Describe the bug**
At `Line 150` and `Line 154` in `packages/zilliqa-js-crypto/src/schnorr.ts`, the `verify` method does not check whether `r` and `s` values are non-negative. Modified code should look like this:
```
  if (sig.s.isZero() || sig.r.isZero()) {
    throw new Error('Invalid signature');
  }
  if (sig.s.isNeg() || sig.r.isNeg()) {
    throw new Error('Invalid signature');
  }
  if (sig.s.gte(curve.n) || sig.r.gte(curve.n)) {
    throw new Error('Invalid signature');
}
```
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iantanwx** [comment]
Fixed by 5dcc59c
