### ISSUE TITLE
Should we add "_sender" and "_amount" as msg default params?

### ISSUE THREAD

**Issue by neeboo** [Zilliqa/Zilliqa-JavaScript-Library#97]
in `contract.ts`

const msg = {
      _tag: transition,
      _sender: `0x${signer_address}`,// is _sender required by transaction call?
      _amount: `amount.toString()`,// _amount also as input?
     ...
      params
    }

**Comment by AmritKumar** [comment]
`_sender` and `_amount` should be inferred from the other fields in the transaction.

**Comment by neeboo** [comment]
OK
