### ISSUE TITLE
help wanting with bundling into one javascript file

### ISSUE THREAD

**Issue by AndreiD** [Zilliqa/Zilliqa-JavaScript-Library#99]
Hello,

I need to import the zilliqa javascript library into an android project (JAVA 8, native). The problem is that node js doesn't work there so I need "simple vanilla" javascript files.

My question is, what commands should I write to create one big javascript file containing all the smaller files that are generated (chain.js, types.js, network.js etc.) ?

similar to the old zilliqa-js library that was deprecated 1 week ago

**Comment by Sajjon** [comment]
@AndreiD Hmm I'm terribly bad at Javascript but I'm a decent Android dev. I'm just curious, how did you plan to invoke Javascript code from Java (or Kotlin)? Is that easy?

**Comment by AndreiD** [comment]
you can do javascript callbacks. you make a 1px webview... or rhino  see https://droidmentor.com/bind-javascript-to-android/

**Comment by AndreiD** [comment]
thanks to neeboo for his help. fixed it
